name: Github Actions

on:
  push:
    branches:
      - master


jobs:
  flutter_test:
    name: Run Flutter
  runs-on: macos-latest
  steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        jav-version: '12.x'

    - uses: subosito/flutter-action@v1
      with:
        channel :'stable'
    - run: flutter pub get
    - run: flutter analyze

  build_android:
    name: Android
    needs: [flutter_test]
    runs_on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          jav-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel :'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk

  build_ios:
    name: IOS
    needs: [flutter_test]
    runs_on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          jav-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          channel:'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build ios